### ISSUE TITLE
Not found trying to download resultUrl

### ISSUE THREAD

**Issue by joseagaleanoc** [smidyo/vectorexpress-api#4] opened 2022-09-06 19:10 UTC
I am sending this petition with headers and data set in the request:
`https://vector.express/api/v2/public/convert/dwg/cad2svg/svg?cad2svg-layers=POLY-TEN`
The result of the request is:
`{"id":"9d219ff3-aa7d-4726-b29c-49b4d44d61e5","inputUrl":"https://vector.express/api/v2/public/files/1f1b0adf-a08f-4c55-a7a8-f8bcdefffc8f.dwg","resultUrl":"https://vector.express/api/v2/public/files/357784ee-15a2-4373-8e9e-99b4fa7d5222.svg","time":4469,"format":"svg","tasks":[{"resultUrl":"https://vector.express/api/v2/public/files/357784ee-15a2-4373-8e9e-99b4fa7d5222.svg","format":"svg","time":4464}]}`
When I cURL the resultURL, I get that Not found: 
`curl https://vector.express/api/v2/public/files/357784ee-15a2-4373-8e9e-99b4fa7d5222.svg --output converted.svg`

**Comment by corrideat** [comment] 2022-09-06 20:07
Hi @joseagaleanoc 

How long has elapsed between the conversion and the download? And can you reproduce the issue?

**Comment by joseagaleanoc** [comment] 2022-09-06 20:28
It was immediately that I tried to download the file. Here's the output for the new request:
`{"id":"afda2f9b-59d0-47e9-a0cd-e7178bf4dc4b","inputUrl":"https://vector.express/api/v2/public/files/68f5e987-7881-473f-b8aa-b3ebb4eecf0d.dwg","resultUrl":"https://vector.express/api/v2/public/files/5736827b-1c29-41f8-8727-19afa8d90d42.svg","time":4560,"format":"svg","tasks":[{"resultUrl":"https://vector.express/api/v2/public/files/5736827b-1c29-41f8-8727-19afa8d90d42.svg","format":"svg","time":4550}]}`

**Comment by isalgadof** [comment] 2023-08-15 18:43
Is any new information available on this issue? It is currently rendering the endpoint completely useless, all result URLs are not found (and if you try too much to access, you'll get cap-locked)

**Comment by corrideat** [comment] 2023-08-15 18:49
Hi @isalgadof,

Unfortunately, there is no new information available as we haven't been able to reproduce the issue. If you're able to, it'd help to provide us with a step-by-step guide that we can also reproduce.

Ideally we need:

1. Full URL of the initial request
2. Full response you receive back
3. Original file sent in the initial request (if you don't want to share publicly, upload it somewhere and share a link to our email (you can find it in our [pricing page](https://vector.express/pricing))

**Comment by isalgadof** [comment] 2023-08-15 19:16
Of course! 

We are trying to convert a DXF to SVG, passed through from client to serverside-endpoint via Multer (as we are using Next.js and have a strict file limit for APIs). From there, we import vectorExpress and send the .convert request:

`const convertedURL = await vectorExpress.convert(input, output, { file:file });
const convertedResponse = await fetch(convertedURL);
            if (!convertedResponse.ok) {
                return res.status(500).json({ error: 'Error obteniendo el archivo convertido' });
            }
            const convertedFileBuffer = await convertedResponse.arrayBuffer();

            res.status(200).send(Buffer.from(convertedFileBuffer));`


The full res i get is: 

`{
  status: 201,
  statusText: 'Created',
  headers: AxiosHeaders {
    date: 'Tue, 15 Aug 2023 19:15:44 GMT',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '404',
    connection: 'close',
    'x-powered-by': 'Express',
    'x-ratelimit-limit': '5',
    'x-ratelimit-remaining': '2',
    'x-ratelimit-reset': '1692130235',
    location: 'https://vector.express/api/v2/public/files/b031a387-61cc-4ff5-b8d4-2688c032be7e.svg',
    etag: 'W/"194-relTnP7ijg7hCm+PU/z4MshCYW0"',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'cf-cache-status': 'DYNAMIC',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=V7m3sTABxouw%2B2RV4OlDV1XehM94KUZg0kbdsKq1i6y3LdsM5yJLWFfVnjOo6WzZnvtK7jhEiQIRnr55rwNWormBs3TU8PafaSNYcimf6GYLZ3UOIShxX7sp51YR1QC78w%2F15astwzy2KFKTcA%3D%3D"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    'x-content-type-options': 'nosniff',
    server: 'cloudflare',
    'cf-ray': '7f73c46739eeab31-EZE',
    'alt-svc': 'h3=":443"; ma=86400'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.4.0',
      'Content-Length': '392214',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'https://vector.express/api/v2/public/convert/dxf/cad2svg/svg',
    method: 'post',
    data: '{"fieldname":"file","originalname":"Wappentier_gross.dxf","encoding":"7bit","mimetype":"application/octet-stream","buffer":{"type":"Buffer","data":[32,32,48,13,10,83,69,67,84,73,79,78,13,10,32,32,50,13,10,72,69,65,68,69,82,13,10,32,32,57,13,10,36,65,67,65,68,86,69,82,13,10,32,32,49,13,10,65,67,49,48,50,52,13,10,32,32,57,13,10,36,65,67,65,68,77,65,73,78,84,86,69,82,13,10,32,55,48,13,10,32,32,32,32,32,54,13,10,32,32,57,13,10,36,68,87,71,67,79,68,69,80,65,71,69,13,10,32,32,51,13,10,77,65,67,45,82,79,77,65,78,13,10,32,32,57,13,10,36,73,78,83,66,65,83,69,13,10,32,49,48,13,10,48,46,48,13,10,32,50,48,13,10,48,46,48,13,10,32,51,48,13,10,48,46,48,13,10,32,32,57,13,10,36,69,88,84,77,73,78,13,10,32,49,48,13,10,49,46,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,69,43,50,48,13,10,32,50,48,13,10,49,46,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,69,43,50,48,13,10,32,51,48,13,10,49,46,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,69,43,50,48,13,10,32,32,57,13,10,36,69,88,84,77,65,88,13,10,32,49,48,13,10,45,49,46,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,69,43,50,48,13,10,32,50,48,13,10,45,49,46,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,69,43,50,48,13,10,32,51,48,13,10,45,49,46,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,69,43,50,48,13,10,32,32,57,13,10,36,76,73,77,77,73,78,13,10,32,49,48,13,10,48,46,48,13,10,32,50,48,13,10,48,46,48,13,10,32,32,57,13,10,36,76,73,77,77,65,88,13,10,32,49,48,13,10,52,50,48,46,48,13,10,32,50,48,13,10,50,57,55,46,48,13,10,32,32,57,13,10,36,79,82,84,72,79,77,79,68,69,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,82,69,71,69,78,77,79,68,69,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,70,73,76,76,77,79,68,69,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,81,84,69,88,84,77,79,68,69,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,77,73,82,82,84,69,88,84,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,76,84,83,67,65,76,69,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,65,84,84,77,79,68,69,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,84,69,88,84,83,73,90,69,13,10,32,52,48,13,10,50,46,53,13,10,32,32,57,13,10,36,84,82,65,67,69,87,73,68,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,84,69,88,84,83,84,89,76,69,13,10,32,32,55,13,10,83,116,97,110,100,97,114,100,13,10,32,32,57,13,10,36,67,76,65,89,69,82,13,10,32,32,56,13,10,48,13,10,32,32,57,13,10,36,67,69,76,84,89,80,69,13,10,32,32,54,13,10,66,121,76,97,121,101,114,13,10,32,32,57,13,10,36,67,69,67,79,76,79,82,13,10,32,54,50,13,10,32,32,32,50,53,54,13,10,32,32,57,13,10,36,67,69,76,84,83,67,65,76,69,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,68,73,83,80,83,73,76,72,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,67,65,76,69,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,68,73,77,65,83,90,13,10,32,52,48,13,10,50,46,53,13,10,32,32,57,13,10,36,68,73,77,69,88,79,13,10,32,52,48,13,10,48,46,54,50,53,13,10,32,32,57,13,10,36,68,73,77,68,76,73,13,10,32,52,48,13,10,51,46,55,53,13,10,32,32,57,13,10,36,68,73,77,82,78,68,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,68,76,69,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,69,88,69,13,10,32,52,48,13,10,49,46,50,53,13,10,32,32,57,13,10,36,68,73,77,84,80,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,84,77,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,84,88,84,13,10,32,52,48,13,10,50,46,53,13,10,32,32,57,13,10,36,68,73,77,67,69,78,13,10,32,52,48,13,10,50,46,53,13,10,32,32,57,13,10,36,68,73,77,84,83,90,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,84,79,76,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,76,73,77,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,73,72,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,79,72,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,69,49,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,69,50,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,65,68,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,68,73,77,90,73,78,13,10,32,55,48,13,10,32,32,32,32,32,56,13,10,32,32,57,13,10,36,68,73,77,66,76,75,13,10,32,32,49,13,10,13,10,32,32,57,13,10,36,68,73,77,65,83,79,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,68,73,77,83,72,79,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,68,73,77,80,79,83,84,13,10,32,32,49,13,10,13,10,32,32,57,13,10,36,68,73,77,65,80,79,83,84,13,10,32,32,49,13,10,13,10,32,32,57,13,10,36,68,73,77,65,76,84,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,65,76,84,68,13,10,32,55,48,13,10,32,32,32,32,32,51,13,10,32,32,57,13,10,36,68,73,77,65,76,84,70,13,10,32,52,48,13,10,48,46,48,51,57,51,55,48,48,55,56,55,52,48,49,54,13,10,32,32,57,13,10,36,68,73,77,76,70,65,67,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,68,73,77,84,79,70,76,13,10,32,55,48,13,10,32,32,32,32,32,49,13,10,32,32,57,13,10,36,68,73,77,84,86,80,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,84,73,88,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,79,88,68,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,65,72,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,66,76,75,49,13,10,32,32,49,13,10,13,10,32,32,57,13,10,36,68,73,77,66,76,75,50,13,10,32,32,49,13,10,13,10,32,32,57,13,10,36,68,73,77,83,84,89,76,69,13,10,32,32,50,13,10,73,83,79,45,50,53,13,10,32,32,57,13,10,36,68,73,77,67,76,82,68,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,67,76,82,69,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,67,76,82,84,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,70,65,67,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,68,73,77,71,65,80,13,10,32,52,48,13,10,48,46,54,50,53,13,10,32,32,57,13,10,36,68,73,77,74,85,83,84,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,68,49,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,83,68,50,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,79,76,74,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,90,73,78,13,10,32,55,48,13,10,32,32,32,32,32,56,13,10,32,32,57,13,10,36,68,73,77,65,76,84,90,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,65,76,84,84,90,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,85,80,84,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,68,69,67,13,10,32,55,48,13,10,32,32,32,32,32,50,13,10,32,32,57,13,10,36,68,73,77,84,68,69,67,13,10,32,55,48,13,10,32,32,32,32,32,50,13,10,32,32,57,13,10,36,68,73,77,65,76,84,85,13,10,32,55,48,13,10,32,32,32,32,32,50,13,10,32,32,57,13,10,36,68,73,77,65,76,84,84,68,13,10,32,55,48,13,10,32,32,32,32,32,51,13,10,32,32,57,13,10,36,68,73,77,84,88,83,84,89,13,10,32,32,55,13,10,83,116,97,110,100,97,114,100,13,10,32,32,57,13,10,36,68,73,77,65,85,78,73,84,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,65,68,69,67,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,65,76,84,82,78,68,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,68,73,77,65,90,73,78,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,68,83,69,80,13,10,32,55,48,13,10,32,32,32,32,52,52,13,10,32,32,57,13,10,36,68,73,77,65,84,70,73,84,13,10,32,55,48,13,10,32,32,32,32,32,51,13,10,32,32,57,13,10,36,68,73,77,70,82,65,67,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,76,68,82,66,76,75,13,10,32,32,49,13,10,13,10,32,32,57,13,10,36,68,73,77,76,85,78,73,84,13,10,32,55,48,13,10,32,32,32,32,32,50,13,10,32,32,57,13,10,36,68,73,77,76,87,68,13,10,32,55,48,13,10,32,32,32,32,45,50,13,10,32,32,57,13,10,36,68,73,77,76,87,69,13,10,32,55,48,13,10,32,32,32,32,45,50,13,10,32,32,57,13,10,36,68,73,77,84,77,79,86,69,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,70,88,76,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,68,73,77,70,88,76,79,78,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,74,79,71,65,78,71,13,10,32,52,48,13,10,48,46,55,56,53,51,57,56,49,54,51,51,57,55,52,52,56,51,13,10,32,32,57,13,10,36,68,73,77,84,70,73,76,76,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,84,70,73,76,76,67,76,82,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,65,82,67,83,89,77,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,68,73,77,76,84,89,80,69,13,10,32,32,54,13,10,13,10,32,32,57,13,10,36,68,73,77,76,84,69,88,49,13,10,32,32,54,13,10,13,10,32,32,57,13,10,36,68,73,77,76,84,69,88,50,13,10,32,32,54,13,10,13,10,32,32,57,13,10,36,68,73,77,84,88,84,68,73,82,69,67,84,73,79,78,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,76,85,78,73,84,83,13,10,32,55,48,13,10,32,32,32,32,32,50,13,10,32,32,57,13,10,36,76,85,80,82,69,67,13,10,32,55,48,13,10,32,32,32,32,32,52,13,10,32,32,57,13,10,36,83,75,69,84,67,72,73,78,67,13,10,32,52,48,13,10,49,46,48,13,10,32,32,57,13,10,36,70,73,76,76,69,84,82,65,68,13,10,32,52,48,13,10,49,48,46,48,13,10,32,32,57,13,10,36,65,85,78,73,84,83,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,65,85,80,82,69,67,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,77,69,78,85,13,10,32,32,49,13,10,46,13,10,32,32,57,13,10,36,69,76,69,86,65,84,73,79,78,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,80,69,76,69,86,65,84,73,79,78,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,84,72,73,67,75,78,69,83,83,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,76,73,77,67,72,69,67,75,13,10,32,55,48,13,10,32,32,32,32,32,48,13,10,32,32,57,13,10,36,67,72,65,77,70,69,82,65,13,10,32,52,48,13,10,48,46,48,13,10,32,32,57,13,10,36,67,72,65,77,70,69,82,66,13,10,32,52,48,13,10,48,46,4'... 382214 more characters
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '392214',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'vector.express',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'vector.express',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 69856,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /api/v2/public/convert/dxf/cad2svg/svg HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/1.4.0\r\n' +
      'Content-Length: 392214\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: vector.express\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/api/v2/public/convert/dxf/cad2svg/svg',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 201,
      statusMessage: 'Created',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://vector.express/api/v2/public/convert/dxf/cad2svg/svg',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 36,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'vector.express',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 392214,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://vector.express/api/v2/public/convert/dxf/cad2svg/svg',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  data: {
    id: '9eb97af3-f384-4aeb-916e-9dec9ad76563',
    inputUrl: 'https://vector.express/api/v2/public/files/5db34a04-d643-40ae-94a9-403b4498679e.dxf',
    resultUrl: 'https://vector.express/api/v2/public/files/b031a387-61cc-4ff5-b8d4-2688c032be7e.svg',
    time: 7213,
    format: 'svg',
    tasks: [ [Object] ]
  }
}`


The returned URL is: https://vector.express/api/v2/public/files/e045cc6f-61d6-44eb-9f73-8143abd81eba.svg


Thank you very much

**Comment by isalgadof** [comment] 2023-08-15 19:20
The file i attempted to convert is: https://drive.google.com/file/d/1MQo7GN24ZOAC9aKuxrcR1RXY7X1deG-H/view?usp=drive_link

**Comment by corrideat** [comment] 2023-08-15 20:20
Hi @isalgadof,

Thank you! There are two issues here:

1) You're getting a success response when you shouldn't (if you try `cadlib`, you correctly get an error response). This we should fix.
2) The file you're sending us is not the correct file (or rather, not in the correct format). You must send the raw file directly as the request body, without any transformations, such as putting in in 'HTML form' format, i.e., do the same as the `--data-binary` file in cURL does.

Your file (the one you uploaded to VX, not the one on Google Drive) starts like this (which you can see in the response you posted above this comment as well):

```
{"fieldname":"file","originalname":"Wappentier_gross.dxf","encoding":"7bit","mimetype":"application/octet-stream","buffer":{"type":"Buffer","data":[32,32,48,13
```

That seems to be some kind of data structure (from a form or something) you're sending. You should be sending what is inside `buffer.data` as raw bytes. The first 16 bytes of your file (on Google Drive) are:

```
00000000  20 20 30 0d 0a 53 45 43  54 49 4f 4e 0d 0a 20 20  |  0..SECTION..  |
```

This is the file correctly converted: https://vector.express/api/v2/public/files/f0fb6542-8370-4f47-8159-7ce4bd569deb.svg (note that it may be deleted soon).

I'll close this issue as it seems to have been resolved.

**Closed as completed by corrideat** 2023-08-15 20:20 UTC

**Comment by isalgadof** [comment] 2023-08-15 20:29
Thank you for your time, we will verify the data structure mismatch and will update with results once we get it working. 

🥰

**Comment by corrideat** [comment] 2023-08-15 20:44
Great!

PS: You can verify what you're sending us in the `"inputUrl"` response field. For example, your file (from GD) is https://vector.express/api/v2/public/files/d6ec691c-8c4d-4efc-83c5-c14acbf4463e.dxf, while your file (that doesn't work) is https://vector.express/api/v2/public/files/9dd12215-4936-4997-aecb-7006e043d78a.dxf.

If the file from inputUrl you download is different from the one you have, it means something went wrong with the upload, _possibly_ on your end.
